-- Tabla de ITEMS
DROP TABLE IF EXISTS ITEMS;

CREATE TABLE ITEMS
	(
	codigo INTEGER NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	PRIMARY KEY(codigo));


-- Tabla de ITEMS con clave AUTO_INCREMENT
DROP TABLE IF EXISTS ITEMS_AUTO;

CREATE TABLE ITEMS_AUTO
	(
	codigo INTEGER NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL,
	PRIMARY KEY(codigo));
	