DROP TABLE IF EXISTS LIGA_PARTIDOS;
DROP TABLE IF EXISTS LIGA_JORNADAS;
DROP TABLE IF EXISTS LIGA_EQUIPOS;

CREATE TABLE LIGA_EQUIPOS
	(
	EQUIPO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	EQUIPO VARCHAR(10)  NOT NULL ,
	PRIMARY KEY(EQUIPO_ID)  
	);

CREATE TABLE LIGA_JORNADAS
	(
	JORNADA_ID INTEGER NOT NULL AUTO_INCREMENT ,
	FECHA DATE ,
	PRIMARY KEY(JORNADA_ID)  
	);
	
CREATE TABLE LIGA_PARTIDOS
	(
	PARTIDO_ID INTEGER NOT NULL AUTO_INCREMENT,
	JORNADA_ID INTEGER NOT NULL,
	LOCAL_ID INTEGER,
	VISITANTE_ID INTEGER,
	MARCADOR_LOCAL INTEGER NOT NULL DEFAULT 0,
	MARCADOR_VISITANTE INTEGER NOT NULL DEFAULT 0,
	ESTADO CHAR,
	PRIMARY KEY(PARTIDO_ID),
	FOREIGN KEY ( JORNADA_ID ) REFERENCES LIGA_JORNADAS( JORNADA_ID ),
	FOREIGN KEY ( LOCAL_ID ) REFERENCES LIGA_EQUIPOS( EQUIPO_ID ),
	FOREIGN KEY ( VISITANTE_ID ) REFERENCES LIGA_EQUIPOS( EQUIPO_ID ) 
	);
	
INSERT INTO LIGA_EQUIPOS ( EQUIPO) VALUES ( 'MADRID');
INSERT INTO LIGA_EQUIPOS ( EQUIPO) VALUES ( 'BARCELONA');
INSERT INTO LIGA_EQUIPOS ( EQUIPO) VALUES ( 'VALENCIA');
INSERT INTO LIGA_EQUIPOS ( EQUIPO) VALUES ( 'MALAGA');
INSERT INTO LIGA_EQUIPOS ( EQUIPO) VALUES ( 'MURCIA');
INSERT INTO LIGA_EQUIPOS ( EQUIPO) VALUES ( 'ALMERIA');
INSERT INTO LIGA_EQUIPOS ( EQUIPO) VALUES ( 'BILBAO');
INSERT INTO LIGA_EQUIPOS ( EQUIPO) VALUES ( 'ZARAGOZA');

INSERT INTO LIGA_JORNADAS ( FECHA ) VALUES ( "2014-10-10");
INSERT INTO LIGA_JORNADAS ( FECHA ) VALUES ( "2014-10-17");


INSERT INTO LIGA_PARTIDOS (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '1', '2', '0', '0', 'F');
INSERT INTO LIGA_PARTIDOS (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '3', '4', '7', '0', 'F');
INSERT INTO LIGA_PARTIDOS (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '5', '6', '1', '0', 'F');
INSERT INTO LIGA_PARTIDOS (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '7', '8', '0', '0', 'F');

INSERT INTO LIGA_PARTIDOS (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '2', '3', '2', '1', '5', 'F');
INSERT INTO LIGA_PARTIDOS (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '2', '1', '4', '2', '0', 'F');
INSERT INTO LIGA_PARTIDOS (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '5', '7', '0', '1', 'F');
INSERT INTO LIGA_PARTIDOS (JORNADA_ID, LOCAL_ID, VISITANTE_ID, MARCADOR_LOCAL, MARCADOR_VISITANTE, ESTADO) VALUES ( '1', '6', '8', '1', '0', 'F');

